# lychee.toml

exclude = [
    "http://localhost",
    "https://localhost:8000",
    "http://127.0.0.1",
    "https://domain.com"
    ".*linkedin\.com.*"
]

accept = ["200..=299", "429", "403", "999"]

timeout = 20

max_retries = 2
