# lychee.toml

exclude_urls = [
    "http://localhost",
    "https://localhost:8000",
    "http://127.0.0.1",
    "https://domain.com"
]

accept = [200, 429, 403]

timeout = 20

max_retries = 2

exclude_mail = true
