name: Link Checker (Lychee)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Restoring Cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Executar Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --cache --max-cache-age 1d "**/*.md" "**/*.html" "**/*.blade.php" "**/*Seeder.php" "**/seeders/*.php"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
